# data.py — All the music rankings data lives here

rankings_data = {
    "January": {
        "Songs": [
            {"name": "Blinding Lights", "minutes": 320, "image": "https://picsum.photos/seed/s1/100/100"},
            {"name": "Save Your Tears", "minutes": 290, "image": "https://picsum.photos/seed/s2/100/100"},
            {"name": "Levitating", "minutes": 275, "image": "https://picsum.photos/seed/s3/100/100"},
            {"name": "Peaches", "minutes": 260, "image": "https://picsum.photos/seed/s4/100/100"},
            {"name": "Good 4 U", "minutes": 245, "image": "https://picsum.photos/seed/s5/100/100"},
            {"name": "Stay", "minutes": 230, "image": "https://picsum.photos/seed/s6/100/100"},
            {"name": "Montero", "minutes": 215, "image": "https://picsum.photos/seed/s7/100/100"},
            {"name": "Kiss Me More", "minutes": 200, "image": "https://picsum.photos/seed/s8/100/100"},
            {"name": "Butter", "minutes": 185, "image": "https://picsum.photos/seed/s9/100/100"},
            {"name": "Leave The Door Open", "minutes": 170, "image": "https://picsum.photos/seed/s10/100/100"},
        ],
        "Artists": [
            {"name": "The Weeknd", "minutes": 610, "image": "https://picsum.photos/seed/a1/100/100"},
            {"name": "Dua Lipa", "minutes": 540, "image": "https://picsum.photos/seed/a2/100/100"},
            {"name": "Justin Bieber", "minutes": 490, "image": "https://picsum.photos/seed/a3/100/100"},
            {"name": "Olivia Rodrigo", "minutes": 460, "image": "https://picsum.photos/seed/a4/100/100"},
            {"name": "BTS", "minutes": 420, "image": "https://picsum.photos/seed/a5/100/100"},
            {"name": "Lil Nas X", "minutes": 390, "image": "https://picsum.photos/seed/a6/100/100"},
            {"name": "Silk Sonic", "minutes": 360, "image": "https://picsum.photos/seed/a7/100/100"},
            {"name": "Doja Cat", "minutes": 330, "image": "https://picsum.photos/seed/a8/100/100"},
            {"name": "Tyler the Creator", "minutes": 300, "image": "https://picsum.photos/seed/a9/100/100"},
            {"name": "Billie Eilish", "minutes": 270, "image": "https://picsum.photos/seed/a10/100/100"},
        ],
        "Genres": [
            {"name": "Pop", "minutes": 1200, "image": "https://picsum.photos/seed/g1/100/100"},
            {"name": "R&B", "minutes": 980, "image": "https://picsum.photos/seed/g2/100/100"},
            {"name": "Hip-Hop", "minutes": 870, "image": "https://picsum.photos/seed/g3/100/100"},
            {"name": "Electronic", "minutes": 740, "image": "https://picsum.photos/seed/g4/100/100"},
            {"name": "Indie", "minutes": 620, "image": "https://picsum.photos/seed/g5/100/100"},
            {"name": "Rock", "minutes": 510, "image": "https://picsum.photos/seed/g6/100/100"},
            {"name": "Latin", "minutes": 430, "image": "https://picsum.photos/seed/g7/100/100"},
            {"name": "Jazz", "minutes": 350, "image": "https://picsum.photos/seed/g8/100/100"},
            {"name": "Classical", "minutes": 270, "image": "https://picsum.photos/seed/g9/100/100"},
            {"name": "K-Pop", "minutes": 190, "image": "https://picsum.photos/seed/g10/100/100"},
        ],
    },
    "February": {
        "Songs": [
            {"name": "Heat Waves", "minutes": 340, "image": "https://picsum.photos/seed/f1/100/100"},
            {"name": "Easy On Me", "minutes": 310, "image": "https://picsum.photos/seed/f2/100/100"},
            {"name": "Industry Baby", "minutes": 295, "image": "https://picsum.photos/seed/f3/100/100"},
            {"name": "Shivers", "minutes": 278, "image": "https://picsum.photos/seed/f4/100/100"},
            {"name": "Bad Habits", "minutes": 260, "image": "https://picsum.photos/seed/f5/100/100"},
            {"name": "Fancy Like", "minutes": 242, "image": "https://picsum.photos/seed/f6/100/100"},
            {"name": "Permission to Dance", "minutes": 225, "image": "https://picsum.photos/seed/f7/100/100"},
            {"name": "Smokin Out The Window", "minutes": 208, "image": "https://picsum.photos/seed/f8/100/100"},
            {"name": "Need To Know", "minutes": 191, "image": "https://picsum.photos/seed/f9/100/100"},
            {"name": "Happier Than Ever", "minutes": 174, "image": "https://picsum.photos/seed/f10/100/100"},
        ],
        "Artists": [
            {"name": "Glass Animals", "minutes": 640, "image": "https://picsum.photos/seed/fa1/100/100"},
            {"name": "Adele", "minutes": 580, "image": "https://picsum.photos/seed/fa2/100/100"},
            {"name": "Ed Sheeran", "minutes": 510, "image": "https://picsum.photos/seed/fa3/100/100"},
            {"name": "Lil Nas X", "minutes": 475, "image": "https://picsum.photos/seed/fa4/100/100"},
            {"name": "BTS", "minutes": 440, "image": "https://picsum.photos/seed/fa5/100/100"},
            {"name": "Walker Hayes", "minutes": 400, "image": "https://picsum.photos/seed/fa6/100/100"},
            {"name": "Silk Sonic", "minutes": 365, "image": "https://picsum.photos/seed/fa7/100/100"},
            {"name": "Doja Cat", "minutes": 330, "image": "https://picsum.photos/seed/fa8/100/100"},
            {"name": "Billie Eilish", "minutes": 295, "image": "https://picsum.photos/seed/fa9/100/100"},
            {"name": "Olivia Rodrigo", "minutes": 260, "image": "https://picsum.photos/seed/fa10/100/100"},
        ],
        "Genres": [
            {"name": "Pop", "minutes": 1300, "image": "https://picsum.photos/seed/fg1/100/100"},
            {"name": "Hip-Hop", "minutes": 1050, "image": "https://picsum.photos/seed/fg2/100/100"},
            {"name": "R&B", "minutes": 900, "image": "https://picsum.photos/seed/fg3/100/100"},
            {"name": "Indie", "minutes": 760, "image": "https://picsum.photos/seed/fg4/100/100"},
            {"name": "Electronic", "minutes": 630, "image": "https://picsum.photos/seed/fg5/100/100"},
            {"name": "Rock", "minutes": 520, "image": "https://picsum.photos/seed/fg6/100/100"},
            {"name": "Country", "minutes": 440, "image": "https://picsum.photos/seed/fg7/100/100"},
            {"name": "Latin", "minutes": 360, "image": "https://picsum.photos/seed/fg8/100/100"},
            {"name": "Jazz", "minutes": 280, "image": "https://picsum.photos/seed/fg9/100/100"},
            {"name": "Soul", "minutes": 200, "image": "https://picsum.photos/seed/fg10/100/100"},
        ],
    },
}